
TYPE
	AxisStates_enum : 
		(
		STATE_INIT := 0, (*INICIO DE SECUENCIA DEL EJE*)
		STATE_CONFIG := 10, (*CONFIGURACION DEL EJE*)
		STATE_POWER_ON := 20, (*ENCIENDE EL DRIVE*)
		STATE_ERROR := 9000 (*EJE EN ERROR*)
		);
	ConfigStates_enum : 
		(
		CONFIG_LOAD_REQ := 100,
		CONFIG_LOAD_DONE := 200,
		CONFIG_SAVE_REQ := 300,
		CONFIG_SAVE_DONE := 400
		);
END_TYPE
