
TYPE
	AxisStates_enum : 
		(
		STATE_INIT := 0, (*INICIO DE SECUENCIA DEL EJE*)
		STATE_CONFIG := 10, (*CONFIGURACION DEL EJE*)
		STATE_POWER_ON := 20, (*ENCIENDE EL DRIVE*)
		STATE_HOME := 30, (*HOMING DEL EJE*)
		STATE_IDLE := 40, (*EJE LISTO PARA OPERAR*)
		STATE_JOG := 50, (*EJE EN MODO JOG*)
		STATE_MOVE_ABSOLUTE := 60, (*MODO DE OPERACION MOVIMIENTO ABSOLUTO*)
		STATE_MOVE_ADDITIVE := 70, (*MODO DE OPERACION MOVIMIENTO ADITIVO*)
		STATE_ERROR := 9000 (*EJE EN ERROR*)
		);
	ConfigStates_enum : 
		(
		CONFIG_LOAD_REQ := 100,
		CONFIG_LOAD_DONE := 200,
		CONFIG_SAVE_REQ := 300,
		CONFIG_SAVE_DONE := 400
		);
	HomeState_enum : 
		(
		HOME_CONFIG,
		HOME_CONFIG_DONE,
		HOME_REQ,
		HOME_DONE
		);
	JogStates_enum : 
		(
		JOG_CONFIG_REQ := 100,
		JOG_CONFIG_DONE := 200,
		JOG_WAIT := 300,
		JOG_EXECUTE := 400,
		JOG_SAFE_STOP := 500,
		JOG_DONE := 600
		);
	AbsoluteMov_enum : 
		(
		MOVE_ABSOLUTE_CONFIG := 100,
		MOVE_ABSOLUTE_WAIT := 200,
		MOVE_ABSOLUTE_EXECUTE := 300,
		MOVE_ASOLUTE_IN_POSITION := 400,
		MOVE_ABSOLUTE_DONE := 500
		);
	AdditiveMov_enum : 
		(
		MOVE_ADDITIVE_CONFIG,
		MOVE_ADDITIVE_WAIT,
		MOVE_ADDITIVE_EXECUTE,
		MOVE_ADDITIVE_IN_POSITION,
		MOVE_ADDITIVE_DONE
		);
END_TYPE
